name: dart_application_1test
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.4

# Add regular dependencies here.
dependencies:
  carousel_slider: ^4.2.1
  circular_countdown_timer: ^0.2.3
  convex_bottom_bar: ^3.2.0
  flutter_custom_clippers: ^2.1.0
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.6.0
  get: ^4.6.6
  google_fonts: ^6.1.0
  hive_generator: ^2.0.1
  lottie: ^2.7.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  timer_count_down: ^2.2.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
