name: dart_application_1test
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.4

# Add regular dependencies here.
dependencies:
  carousel_slider: ^4.2.1
  convex_bottom_bar: ^3.2.0
  flutter_custom_clippers: ^2.1.0
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
